# Generated by Django 5.2.9 on 2025-12-17 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgicalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('liturgical_year', models.CharField(blank=True, choices=[('A', 'Year A'), ('B', 'Year B'), ('C', 'Year C')], help_text='Liturgical cycle for the readings (A/B/C).', max_length=1)),
                ('season', models.CharField(blank=True, choices=[('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('easter', 'Easter'), ('ordinary', 'Ordinary Time'), ('other', 'Other')], help_text='Liturgical season for this date.', max_length=20)),
                ('rank', models.CharField(blank=True, choices=[('weekday', 'Weekday'), ('sunday', 'Sunday'), ('feast', 'Feast'), ('memorial', 'Memorial'), ('optional_memorial', 'Optional Memorial'), ('solemnity', 'Solemnity')], help_text='Liturgical rank (Sunday, solemnity, feast, etc.).', max_length=20)),
                ('is_holy_day_of_obligation', models.BooleanField(default=False, help_text='Indicates if this date is a holy day of obligation in the selected calendar.')),
            ],
            options={
                'verbose_name': 'Liturgical day',
                'verbose_name_plural': 'Liturgical days',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='GospelMeditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], help_text='Language of this meditation.', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Full meditation text for the daily gospel.')),
                ('source', models.CharField(choices=[('ai', 'AI generated'), ('human', 'Human written'), ('other', 'Other')], default='ai', help_text='Indicates whether this meditation was generated by AI or written by a person.', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Approval status. Only approved meditations should be shown publicly.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when this meditation was approved.', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meditations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meditations', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to='readings.liturgicalday')),
            ],
            options={
                'verbose_name': 'Gospel meditation',
                'verbose_name_plural': 'Gospel meditations',
                'ordering': ('day', 'language_code', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('day', 'language_code'), name='unique_approved_meditation_per_day_language')],
            },
        ),
        migrations.CreateModel(
            name='DailyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], help_text='Language of this reading.', max_length=10)),
                ('reading_type', models.CharField(choices=[('first_reading', 'First reading'), ('responsorial_psalm', 'Responsorial psalm'), ('second_reading', 'Second reading'), ('gospel_acclamation', 'Gospel acclamation'), ('gospel', 'Gospel'), ('other', 'Other')], help_text='Type of reading (gospel, psalm, etc.).', max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Order of the reading when there are multiple of the same type.')),
                ('title', models.CharField(blank=True, help_text='Optional heading/title for display.', max_length=255)),
                ('reference', models.CharField(help_text='Scripture reference, e.g. "Jn 3,16-18".', max_length=255)),
                ('psalm_response', models.CharField(blank=True, help_text='Used for the responsorial psalm refrain (R/.).', max_length=255)),
                ('text', models.TextField(help_text='Full text of the reading in the selected language.')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='readings.liturgicalday')),
            ],
            options={
                'verbose_name': 'Daily reading',
                'verbose_name_plural': 'Daily readings',
                'ordering': ('day', 'language_code', 'reading_type', 'order'),
                'constraints': [models.UniqueConstraint(fields=('day', 'language_code', 'reading_type', 'order'), name='unique_reading_per_day_language_type_order')],
            },
        ),
    ]
